post:
  frontend-url: "https://localhost:3000"
  http-masking-turned-on: true
server:
  ssl:
    key-store: classpath:blog.p12
    key-store-password: ${ssl_blog_passphrase}
    key-store-type: pkcs12
    key-alias: blog
    key-password: ${ssl_blog_passphrase}
spring:
  data:
    redis:
      host: redis
      port: 6379
      cacheName: jwtBlacklist
  datasource:
    url: jdbc:postgresql://postgres:5432/posts
    username: posts
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase/postgresql/changelog/liquibase.changelog_master.yaml

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true