post:
  frontend-url: ${frontend_url}
  http-masking-turned-on: true
server:
  ssl:
    key-store: classpath:blog.p12
    key-store-password: ${ssl_blog_passphrase}
    key-store-type: pkcs12
    key-alias: blog
    key-password: ${ssl_blog_passphrase}
minio:
  url: ${minio_url}
  bucket: posts
  username: admin
  password: ${minio_password}
spring:
  datasource:
    url: jdbc:postgresql://${postgres_post_url}/posts
    username: posts
    password: ${postgres_post_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  liquibase:
    change-log: classpath:/liquibase/postgresql/changelog/liquibase.changelog_master.yaml

management:
  endpoint:
    prometheus:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: false